<?php
/**
 * Created by PhpStorm.
 * User: bobchu
 * Date: 15/11/12
 * Time: 下午8:42
 */
namespace Mobile\Controller;
use Think\Controller;

class ProfileController extends BaseController {
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->isLogin();
    }

    /**
     * 修改密码
     */
    public function editPasswd(){
        $this->display();
    }

    /**
     * 执行修改密码
     */
    public function updatePasswd(){
        $user_info = session('user_info');
        if($user_info['password'] == md5($_POST['password'])){
            M('user')->data(array('password'=>md5($_POST['new_password']), 'update_time'=>time()))->where(array('id'=>$user_info['uid']))->save();
            session('user_info', null);
            cookie('user_info', null);
            $this->ajaxReturn(array('status'=>1, 'msg'=>'密码修改成功,请使用新密码重新登录!'));
        }else{
            $this->ajaxReturn(array('status'=>0, 'msg'=>'原密码不正确,请重新输入!'));
        }
    }

    /**
     * 修改资料
     */
    public function editProfile(){
        $user_info = session('user_info');
        $user_address = M('user_address')->where(array('uid'=>$user_info['uid']))->find();
        $this->assign('user_address', $user_address);
        $this->display();
    }

    /**
     * 执行修改资料
     */
    public function updateProfile(){
        $user_address = M('user_address')->where(array('uid'=>$this->uid))->find();
        if($user_address){
            M('user_address')->data($_POST)->where(array('uid'=>$this->uid))->save();
        }else{
            $_POST['uid'] = $this->uid;
            M('user_address')->data($_POST)->add();
        }
        $this->ajaxReturn(array('status'=>1, 'msg'=>'收货地址更新成功!'));
    }
}