<?php
/**
 * 优惠券管理.
 * User: bobchu
 * Date: 15/12/3
 * Time: 11:13
 */
namespace Admin\Controller;

use Think\Db;
use \Common\Libs\Database;
use \Common\Libs\GoodsCategory;
use Think\Model;

class CouponsController extends AdminCoreController {
    public $is_do_words = array('未使用', '已使用');
    /**
     * 初始化
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 管理列表
     */
    public function index(){
        if(IS_POST){
            $post_data=I('post.');
            $post_data['first'] = $post_data['rows'] * ($post_data['page'] - 1);
            $map = array();
            $total = M('coupons')->where($map)->count();
            if($total==0){
                $_list='';
            }else{
                $_list = M('coupons')->where($map)->limit($post_data['first'].','.$post_data['rows'])->select();
            }

            foreach($_list as $list_key=>$list_one){
                $_list [$list_key]["ctime"]=date("Y年m月d日 H:i:s",$_list[$list_key]["ctime"]);
                $_list [$list_key]["utime"]=date("Y年m月d日 H:i:s",$_list[$list_key]["utime"]);
                $operate_menu='';
                if(Is_Auth('Admin/Coupons/edit')){
                    $operate_menu = $operate_menu."<a href='#' onclick=\"Submit_Form('Coupons_Form','Coupons_Data_List','" . U ( 'edit', array ('id' => $_list [$list_key] ['id'] ) ) . "','','编辑优惠券','');\">编辑</a>";
                }
                if(Is_Auth('Admin/Coupons/del')){
                    $operate_menu = $operate_menu."<a href='#' onclick=\"Data_Remove('" . U ( 'del', array ('id' => $_list [$list_key] ['id'] ) ) . "','Coupons_Data_List');\">删除</a>";
                }
                $_list [$list_key] ['operate'] = $operate_menu;
            }
            $data = array('total'=>$total, 'rows'=>$_list);
            $this->ajaxReturn($data);
        }else{
            $this->assign('stores_type', M('stores_type')->select());
            $this->display();
        }
    }

    /**
     * 添加优惠券
     */
    public function add(){
        if(IS_POST){
            if(empty($_POST['name'])){
                $this->error('优惠券名称不能为空!');
            }
            if(empty($_POST['price'])){
                $this->error('优惠券金额不能为空!');
            }
            if(!is_numeric($_POST['price'])){
                $this->error('优惠券金额必须是数字!');
            }
            if(empty($_POST['meet_price'])){
                $this->error('满足金额不能为空!');
            }
            if(!is_numeric($_POST['meet_price'])){
                $this->error('满足金额必须是数字!');
            }
            $data['price'] = $_POST['price'];
            $data['meet_price'] = $_POST['meet_price'];
            $data['name'] = $_POST['name'];
            $data['ctime'] = time();
            $data['utime'] = $data['ctime'];
            $coupons_id = M("coupons")->data($data)->add();
            if($coupons_id){
                $this->success('优惠券添加成功!');
            }else{
                $this->error('优惠券添加失败!');
            }
        }else{
            $this->display();
        }
    }

    /**
     * 编辑优惠券
     */
    public function edit(){
        if(IS_POST){
            if(empty($_POST['name'])){
                $this->error('优惠券名称不能为空!');
            }
            if(empty($_POST['price'])){
                $this->error('优惠券金额不能为空!');
            }
            if(!is_numeric($_POST['price'])){
                $this->error('优惠券金额必须是数字!');
            }
            if(empty($_POST['meet_price'])){
                $this->error('满足金额不能为空!');
            }
            if(!is_numeric($_POST['meet_price'])){
                $this->error('满足金额必须是数字!');
            }
            $data['price'] = $_POST['price'];
            $data['meet_price'] = $_POST['meet_price'];
            $data['name'] = $_POST['name'];
            $data['utime'] = time();
            M('coupons')->data($data)->where(array('id'=>$_POST['coupons_id']))->save();
            $this->success('优惠券更新成功!');
        }else{
            $info = M('coupons')->where(array('id'=>$_GET['id']))->find();
            $this->assign('info', $info);
            $this->display();
        }
    }

    /**
     * 删除优惠券
     */
    public function del(){

        $id=I('get.id');
        empty($id)&&$this->error('参数不能为空！');
        $res=M('coupons')->delete($id);
        if(!$res){
            $this->error('删除失败！');
        }else{
            action_log('Del_Coupons', 'Coupons', $id);
            $this->success('删除成功！');
        }
    }

    /**
     * 用户优惠券列表
     */
    public function user(){
        if(IS_POST){
            $post_data=I('post.');
            $post_data['first'] = $post_data['rows'] * ($post_data['page'] - 1);
            $map = array();
            $map = $this->_search();
            $total = M('user_coupons')->where($map)->count();
            if($total==0){
                $_list='';
            }else{
                $_list = M('user_coupons')->where($map)->limit($post_data['first'].','.$post_data['rows'])->select();
            }

            foreach($_list as $list_key=>$list_one){
                $_list [$list_key]["ctime"]=date("Y年m月d日 H:i:s",$_list[$list_key]["ctime"]);
                if($_list [$list_key]["dtime"]){
                    $_list [$list_key]["dtime"]=date("Y年m月d日 H:i:s",$_list[$list_key]["dtime"]);
                }else{
                    $_list [$list_key]["dtime"]='未使用';
                }
                $_list [$list_key]["is_do"]=$this->is_do_words[$_list[$list_key]['is_do']];
                $_list [$list_key]["give_user_name"]=M('user')->where(array('id'=>$_list[$list_key]['give_uid']))->getField('username');
                $_list [$list_key]["user_name"]=M('user')->where(array('id'=>$_list[$list_key]['uid']))->getField('username');
                $operate_menu='';
                if(Is_Auth('Admin/Coupons/delUserCoupons')){
                    $operate_menu = $operate_menu."<a href='#' onclick=\"Data_Remove('" . U ( 'delUserCoupons', array ('id' => $_list [$list_key] ['id'] ) ) . "','Coupons_Data_List');\">删除</a>";
                }
                $_list [$list_key] ['operate'] = $operate_menu;
            }
            $data = array('total'=>$total, 'rows'=>$_list);
            $this->ajaxReturn($data);
        }else{
            $coupons_list = M('coupons')->select();
            $this->assign('coupons_list', $coupons_list);
            $this->display();
        }
    }

    /**
     * 发放优惠券
     */
    public function addUserCoupons(){
        if(IS_POST){
            $data = I('post.');
            $user = M('user')->where(array('id'=>$data['uid']))->find();
            if(!$user){
                $this->error('用户不存在!');
            }
            if($data['coupons_id'] < 0){
                $this->error('请选择优惠券');
            }
            $coupons_info = M('coupons')->where(array('id'=>$data['coupons_id']))->find();
            $data['price'] = $coupons_info['price'];
            $data['meet_price'] = $coupons_info['meet_price'];
            $data['ctime'] = time();
            $data['give_uid'] = getAdminUid();
            $data['name'] = $coupons_info['name'];
            for($i=0;$i<$data['nums'];$i++){
                $user_coupons_id = M('user_coupons')->data($data)->add();
            }
            if($user_coupons_id){
                $this->success('优惠券发放成功!');
            }else{
                $this->error('优惠券发放失败!');
            }
        }else{
            $coupons_list = M('coupons')->select();
            $this->assign('coupons_list', $coupons_list);
            $this->display();
        }
    }

    /**
     * 删除用户优惠券
     */
    public function delUserCoupons(){

        $id=I('get.id');
        empty($id)&&$this->error('参数不能为空！');
        $res=M('user_coupons')->delete($id);
        if(!$res){
            $this->error('删除失败！');
        }else{
            $this->success('删除成功！');
        }
    }

    /**
     * 搜索
     **/
    protected function _search() {
        $map = array ();
        $post_data = I('post.');

        if($post_data['uid']){
            $map['uid'] = $post_data['uid'];
        }
        if($post_data['give_uid']){
            $map['give_uid'] = $post_data['give_uid'];
        }

//        if($post_data['ctime_begin'] && $post_data['ctime_end']){
//            $map['ctime'] = array(array('gt', strtotime($post_data['ctime_begin'])), array('lt', strtotime($post_data['ctime_end'])), 'AND');
//        }


        /* 名称：状态 字段：status 类型：select*/
        if($post_data['is_do'] > 0){
            $map['is_do'] = $post_data['is_do'];
        }

        if($post_data['coupons_id'] > 0){
            $map['coupons_id'] = $post_data['coupons_id'];
        }

        return $map;
    }
}